# Generated by Django 5.0.1 on 2024-01-19 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqltranslator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpt',
            name='frequency_penalty',
            field=models.FloatField(default=0.7, help_text='Frequency Penalty', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='gpt',
            name='presence_penalty',
            field=models.FloatField(default=0.3, help_text='Presence Penalty', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
